/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdeasIndexRouteImport } from './routes/ideas/index'
import { Route as IdeasIdeaIDIndexRouteImport } from './routes/ideas/$ideaID/index'
import { Route as ProtectedUserIndexRouteImport } from './routes/_protected/user/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as IdeasIdeaIDEditIndexRouteImport } from './routes/ideas/$ideaID/edit/index'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIndexRoute = IdeasIndexRouteImport.update({
  id: '/ideas/',
  path: '/ideas/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdeaIDIndexRoute = IdeasIdeaIDIndexRouteImport.update({
  id: '/ideas/$ideaID/',
  path: '/ideas/$ideaID/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedUserIndexRoute = ProtectedUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => ProtectedRoute,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => authRouteRoute,
} as any)
const IdeasIdeaIDEditIndexRoute = IdeasIdeaIDEditIndexRouteImport.update({
  id: '/ideas/$ideaID/edit/',
  path: '/ideas/$ideaID/edit/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ideas/': typeof IdeasIndexRoute
  '/login/': typeof authLoginIndexRoute
  '/register/': typeof authRegisterIndexRoute
  '/user/': typeof ProtectedUserIndexRoute
  '/ideas/$ideaID/': typeof IdeasIdeaIDIndexRoute
  '/ideas/$ideaID/edit/': typeof IdeasIdeaIDEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ideas': typeof IdeasIndexRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/user': typeof ProtectedUserIndexRoute
  '/ideas/$ideaID': typeof IdeasIdeaIDIndexRoute
  '/ideas/$ideaID/edit': typeof IdeasIdeaIDEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/ideas/': typeof IdeasIndexRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/_protected/user/': typeof ProtectedUserIndexRoute
  '/ideas/$ideaID/': typeof IdeasIdeaIDIndexRoute
  '/ideas/$ideaID/edit/': typeof IdeasIdeaIDEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ideas/'
    | '/login/'
    | '/register/'
    | '/user/'
    | '/ideas/$ideaID/'
    | '/ideas/$ideaID/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ideas'
    | '/login'
    | '/register'
    | '/user'
    | '/ideas/$ideaID'
    | '/ideas/$ideaID/edit'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/_protected'
    | '/ideas/'
    | '/(auth)/login/'
    | '/(auth)/register/'
    | '/_protected/user/'
    | '/ideas/$ideaID/'
    | '/ideas/$ideaID/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  IdeasIndexRoute: typeof IdeasIndexRoute
  IdeasIdeaIDIndexRoute: typeof IdeasIdeaIDIndexRoute
  IdeasIdeaIDEditIndexRoute: typeof IdeasIdeaIDEditIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/': {
      id: '/ideas/'
      path: '/ideas'
      fullPath: '/ideas/'
      preLoaderRoute: typeof IdeasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$ideaID/': {
      id: '/ideas/$ideaID/'
      path: '/ideas/$ideaID'
      fullPath: '/ideas/$ideaID/'
      preLoaderRoute: typeof IdeasIdeaIDIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/user/': {
      id: '/_protected/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof ProtectedUserIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/ideas/$ideaID/edit/': {
      id: '/ideas/$ideaID/edit/'
      path: '/ideas/$ideaID/edit'
      fullPath: '/ideas/$ideaID/edit/'
      preLoaderRoute: typeof IdeasIdeaIDEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedUserIndexRoute: typeof ProtectedUserIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedUserIndexRoute: ProtectedUserIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  IdeasIndexRoute: IdeasIndexRoute,
  IdeasIdeaIDIndexRoute: IdeasIdeaIDIndexRoute,
  IdeasIdeaIDEditIndexRoute: IdeasIdeaIDEditIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
